import { test } from "@playwright/test";
import { MainPage } from "../../pages/shopPages/mainPage";
import { LoginPage } from "../../pages/shopPages/loginPage";
import { RegistrationPage } from "../../pages/shopPages/registrationPage";
import { ProductPage } from "../../pages/shopPages/productPage";
import { Cartpage } from "../../pages/shopPages/cartPage";
import { AdressOrderPage } from "../../pages/shopPages/adressOrderPage";
import { faker } from "@faker-js/faker";
import { ShippingMethodPage } from "../../pages/shopPages/shippingMethodPage";
import { PaymentPage } from "../../pages/shopPages/paymentPage";
let address = faker.location.street();
let city = faker.location.city();
let postalCode = faker.location.zipCode();

test("tracking", async ({ page }) => {
  await MainPage.loadPage(page);
  await MainPage.clickSignInButton(page);
  await LoginPage.isLoaded(page);
  await LoginPage.clickRegisterLink(page);
  await RegistrationPage.isLoaded(page);
  await RegistrationPage.pickSocialTitle(page, 1);
  await RegistrationPage.fillFirstNameInput(page);
  await RegistrationPage.fillLastNameInput(page);
  await RegistrationPage.fillBirthdateInput(page);
  await RegistrationPage.fillEmailInput(page);
  await RegistrationPage.fillPasswordInput(page);
  await RegistrationPage.clickOffersCheckbox(page);
  await RegistrationPage.clickNewsletterCheckbox(page);
  await RegistrationPage.clickPolicyCheckbox(page);
  await RegistrationPage.clickSaveButton(page);
  await MainPage.isLoaded(page);
  await MainPage.clickProduct(page, 4);
  await ProductPage.addProductToCart(page);
  await ProductPage.clickProceedToCheckout(page);
  await Cartpage.isLoaded(page);
  await Cartpage.clickCheckoutButton(page);
  await AdressOrderPage.isLoaded(page);
  await AdressOrderPage.fillAddressField(page, address);
  await AdressOrderPage.fillCityField(page, city);
  await AdressOrderPage.fillPostalCodeFiled(page, postalCode);
  await AdressOrderPage.selectState(page, "6");
  await AdressOrderPage.clickContinueButton(page);
  await ShippingMethodPage.isLoaded(page);
  await ShippingMethodPage.fillCommentButton(page, "12345 test");
  await ShippingMethodPage.clickContinueButton(page);
  await PaymentPage.isLoaded(page);
  await PaymentPage.clickPayByBankRaddioButton(page);
  await PaymentPage.clickTermsOfServiceCheckbox(page);
});
