import { test } from "@playwright/test";
import { MainPage } from "../../pages/shopPages/mainPage";
import { ProductPage } from "../../pages/shopPages/productPage";
import { Cartpage } from "../../pages/shopPages/cartPage";
import { AdressOrderPage } from "../../pages/shopPages/adressOrderPage";
import { faker } from "@faker-js/faker";
import { ShippingMethodPage } from "../../pages/shopPages/shippingMethodPage";
import { PaymentPage } from "../../pages/shopPages/paymentPage";
import { PersonalDataPage } from "../../pages/shopPages/personalDataPage";
import { ConfirmedOrderPage } from "../../pages/shopPages/confirmedOrderPage";
import { GuestOrderTracking } from "../../pages/shopPages/guestTrackingPage";
import { GuestTrackingOrder } from "../../pages/shopPages/guestTrackingOrderPage";
let address = faker.location.street();
let city = faker.location.city();
let postalCode = "12345";

test("tracking", async ({ page }) => {
  await MainPage.loadPage(page);
  await MainPage.isLoaded(page);
  await MainPage.clickProduct(page, 4);
  await ProductPage.addProductToCart(page);
  await ProductPage.clickProceedToCheckout(page);
  await Cartpage.isLoaded(page);
  await Cartpage.clickCheckoutButton(page);
  await PersonalDataPage.isLoaded(page);
  await PersonalDataPage.pickSocialTitle(page, 2);
  let firstName = await PersonalDataPage.fillFirstNameInput(page);
  let lastName = await PersonalDataPage.fillLastNameInput(page);
  let mail = await PersonalDataPage.fillEmailInput(page);
  await PersonalDataPage.clickPolicyCheckbox(page);
  await PersonalDataPage.clickContinueButton(page);
  await AdressOrderPage.isLoaded(page);
  await AdressOrderPage.fillAddressField(page, address);
  await AdressOrderPage.fillCityField(page, city);
  await AdressOrderPage.fillPostalCodeFiled(page, postalCode);
  await AdressOrderPage.selectState(page, "6");
  await AdressOrderPage.clickContinueButton(page);
  await ShippingMethodPage.isLoaded(page);
  await ShippingMethodPage.fillCommentButton(page, "12345 test");
  await ShippingMethodPage.clickContinueButton(page);
  await PaymentPage.isLoaded(page);
  await PaymentPage.clickPayByBankRaddioButton(page);
  await PaymentPage.clickTermsOfServiceCheckbox(page);
  await PaymentPage.clickPlaceOrderButton(page);
  await ConfirmedOrderPage.isLoaded(page);
  let orderNumber = await ConfirmedOrderPage.getOrderReferenceNumber(page);
  await ConfirmedOrderPage.clickOrderTracking(page);
  await GuestOrderTracking.isLoaded(page);
  await GuestOrderTracking.fillOrderReferenceInput(page, orderNumber);
  await GuestOrderTracking.fillEmailInput(page, mail);
  await GuestOrderTracking.clickSendButton(page);
  await GuestTrackingOrder.isLoaded(page);
  await GuestTrackingOrder.verifyDeliveryAddressData(page, firstName, lastName);
});
